import * as FT from './fuelTech.js'

export const PUMPS = FT.PUMPS
export const BATTERY_CHARGING = FT.BATTERY_CHARGING
export const EXPORTS = FT.EXPORTS
export const IMPORTS = FT.IMPORTS
export const BIOMASS = FT.BIOMASS
export const DISTILLATE = FT.DISTILLATE
export const BATTERY_DISCHARGING = FT.BATTERY_DISCHARGING
export const HYDRO = FT.HYDRO
export const WIND = FT.WIND
/** TODO: check group names are uniquely defined */
export const COAL = 'group_coal'
export const GAS = 'group_gas'
export const SOLAR = 'group_solar'

export const FUEL_TECH_GROUP = {}
FUEL_TECH_GROUP[COAL] = [FT.BROWN_COAL, FT.BLACK_COAL]
FUEL_TECH_GROUP[GAS] = [FT.GAS_STEAM, FT.GAS_CCGT, FT.GAS_OCGT, FT.GAS_RECIP]
FUEL_TECH_GROUP[SOLAR] = [FT.SOLAR, FT.ROOFTOP_SOLAR]

// Fuel tech group order
export const FUEL_TECH_ORDER = [
  BATTERY_CHARGING,
  PUMPS,
  EXPORTS,
  IMPORTS,
  COAL,
  BIOMASS,
  DISTILLATE,
  GAS,
  BATTERY_DISCHARGING,
  HYDRO,
  WIND,
  SOLAR
]

// Fuel tech group colour
export const FUEL_TECH_GROUP_COLOUR = {}
FUEL_TECH_GROUP_COLOUR[PUMPS] = '#88AFD0'
FUEL_TECH_GROUP_COLOUR[BATTERY_CHARGING] = '#B2DAEF'
FUEL_TECH_GROUP_COLOUR[EXPORTS] = '#977AB1'
FUEL_TECH_GROUP_COLOUR[IMPORTS] = '#44146F'
FUEL_TECH_GROUP_COLOUR[COAL] = '#121212'
FUEL_TECH_GROUP_COLOUR[BIOMASS] = '#A3886F'
FUEL_TECH_GROUP_COLOUR[DISTILLATE] = '#F35020'
FUEL_TECH_GROUP_COLOUR[GAS] = '#F9DCBC'
FUEL_TECH_GROUP_COLOUR[BATTERY_DISCHARGING] = '#00A2FA'
FUEL_TECH_GROUP_COLOUR[HYDRO] = '#4582B4'
FUEL_TECH_GROUP_COLOUR[WIND] = '#417505'
FUEL_TECH_GROUP_COLOUR[SOLAR] = '#F8E71C'

// Fuel tech type
const LOAD = 'load'
const SOURCE = 'source'
export const FUEL_TECH_CATEGORY = {}
FUEL_TECH_CATEGORY[PUMPS] = LOAD
FUEL_TECH_CATEGORY[BATTERY_CHARGING] = LOAD
FUEL_TECH_CATEGORY[EXPORTS] = LOAD
FUEL_TECH_CATEGORY[IMPORTS] = SOURCE
FUEL_TECH_CATEGORY[COAL] = SOURCE
FUEL_TECH_CATEGORY[BIOMASS] = SOURCE
FUEL_TECH_CATEGORY[DISTILLATE] = SOURCE
FUEL_TECH_CATEGORY[GAS] = SOURCE
FUEL_TECH_CATEGORY[BATTERY_DISCHARGING] = SOURCE
FUEL_TECH_CATEGORY[HYDRO] = SOURCE
FUEL_TECH_CATEGORY[WIND] = SOURCE
FUEL_TECH_CATEGORY[SOLAR] = SOURCE

// Fuel tech label
export const FUEL_TECH_LABEL = {}
FUEL_TECH_LABEL[PUMPS] = 'Pumps'
FUEL_TECH_LABEL[BATTERY_CHARGING] = 'Battery (Charging)'
FUEL_TECH_LABEL[EXPORTS] = 'Exports'
FUEL_TECH_LABEL[IMPORTS] = 'Imports'
FUEL_TECH_LABEL[COAL] = 'Coal'
FUEL_TECH_LABEL[BIOMASS] = 'Biomass'
FUEL_TECH_LABEL[DISTILLATE] = 'Distillate'
FUEL_TECH_LABEL[GAS] = 'Gas'
FUEL_TECH_LABEL[BATTERY_DISCHARGING] = 'Battery (Discharging)'
FUEL_TECH_LABEL[HYDRO] = 'Hydro'
FUEL_TECH_LABEL[WIND] = 'Wind'
FUEL_TECH_LABEL[SOLAR] = 'Solar'
